const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const path = require('node:path');

const root = path.resolve(__dirname, '../../..');

test('多嘻噜卡使用永沙式资产管理、左右任务台和五段生产导航', async () => {
  const [index, renderer, bridge, styles, server, logo] = await Promise.all([
    fs.readFile(path.join(root, 'apps/web/index.html'), 'utf8'),
    fs.readFile(path.join(root, 'apps/web/src/renderer.js'), 'utf8'),
    fs.readFile(path.join(root, 'apps/web/src/api-bridge.js'), 'utf8'),
    fs.readFile(path.join(root, 'apps/web/src/styles.css'), 'utf8'),
    fs.readFile(path.join(root, 'apps/api/src/server.js'), 'utf8'),
    fs.stat(path.join(root, 'apps/web/public/duoxiluka-logo.png'))
  ]);
  assert.match(index, /<title>多嘻噜卡科技<\/title>/);
  assert.match(index, /src="\/duoxiluka-logo\.png"/);
  assert.match(index, /data-index="01"[^>]+data-page="assets"[^>]*>素材资产<\/button>/);
  for (const [indexNumber, tab, label] of [['02', 'master', '生成平铺图'], ['03', 'model', '生成模特图'], ['04', 'combination', '组合多SKU图']]) {
    assert.match(index, new RegExp(`data-index="${indexNumber}"[^>]+data-page="childrenwear"[^>]+data-childrenwear-production-nav="${tab}"[^>]*>${label}<`));
    assert.match(index, new RegExp(`data-childrenwear-production-panel="${tab}"`));
  }
  for (const [key, label] of [
    ['childrenwearRealAssetsPath', '实拍产品图'],
    ['childrenwearReferenceAssetsPath', '成品参考图'],
    ['childrenwearModelAssetsPath', '参考模特图'],
    ['childrenwearSceneAssetsPath', '场景参考图'],
    ['childrenwearCombinationAssetsPath', '组合图']
  ]) {
    assert.match(index, new RegExp(`data-childrenwear-library-tab="${key}"`));
    assert.match(index, new RegExp(`data-childrenwear-library="${key}"`));
    assert.match(index, new RegExp(`data-childrenwear-library-folder="${key}"`));
    assert.match(index, new RegExp(`data-childrenwear-folder-list="${key}"`));
    assert.match(index, new RegExp(`data-childrenwear-pagination="${key}"`));
    assert.match(index, new RegExp(`data-select-all-childrenwear-library="${key}"`));
    assert.match(index, new RegExp(`data-analyze-childrenwear-library="${key}"`));
    assert.match(index, new RegExp(`data-delete-childrenwear-library="${key}"`));
    assert.match(index, new RegExp(label));
    assert.match(renderer, new RegExp(`${key}:`));
    assert.match(bridge, new RegExp(`${key}:`));
  }
  assert.match(index, /data-index="05"[^>]+data-page="childrenwear-review"[^>]*>成品审核与下载</);
  assert.match(index, /id="cwMasterSourceGrid"/);
  assert.match(index, /id="cwMasterQueue"/);
  assert.match(index, /data-cw-queue-filter="needs_regeneration"/);
  assert.match(index, /data-cw-batch="approve" data-stage="master"/);
  assert.doesNotMatch(index, /data-cw-batch="mark-issue"/);
  assert.match(index, /data-cw-batch="generate" data-stage="master">生成未出图选中/);
  assert.match(index, /data-cw-batch="regenerate" data-stage="master">重新生成选中/);
  assert.match(index, /id="cwMasterActivity"/);
  assert.match(index, /id="cwModelActivity"/);
  assert.match(index, /id="cwCombinationActivity"/);
  assert.match(index, /id="imageHoverPreviewEnabled"/);
  assert.match(index, /id="workspaceBackgroundColor"[^>]+type="color"/);
  assert.match(index, /id="workspaceBackgroundHex"/);
  assert.match(index, /id="pickWorkspaceBackgroundButton"[^>]*>屏幕取色/);
  assert.match(index, /id="resetWorkspaceBackgroundButton"[^>]*>恢复默认/);
  assert.equal((index.match(/class="cw-queue-filters" data-stage="(?:master|model|combination)"/g) || []).length, 3);
  for (const label of ['平铺图任务筛选', '模特图任务筛选', '组合图任务筛选']) {
    const filterBar = index.match(new RegExp(`<div class="cw-queue-filters"[^>]*aria-label="${label}">([\\s\\S]*?)<\\/div>`))?.[1] || '';
    assert.match(filterBar, /data-cw-queue-date-filter/);
    assert.match(filterBar, /<button class="active"[^>]+data-cw-queue-filter="all"/);
    for (const filter of ['all', 'incomplete', 'ready', 'running', 'pending', 'needs_regeneration', 'approved']) {
      assert.match(filterBar, new RegExp(`data-cw-queue-filter="${filter}"`));
    }
  }
  assert.match(index, /class="cw-review-filters">[\s\S]*?id="cwReviewDateFilter"[\s\S]*?<button class="active"[^>]+data-cw-review-filter="all">全部<\/button><button[^>]+data-cw-review-filter="pending">待审核/);
  assert.match(renderer, /childrenwearReviewFilter: 'all'/);
  assert.match(renderer, /name === 'childrenwear-review' && currentPage !== name/);
  assert.match(renderer, /button\.dataset\.cwReviewFilter === state\.childrenwearReviewFilter/);
  assert.doesNotMatch(index, /id="cwCompareFlag"/);
  assert.doesNotMatch(index, /id="cwReviewFlagSelected"/);
  assert.match(index, /id="cwReviewCompareSelected"/);
  assert.match(index, /id="cwModelQueue"/);
  assert.match(index, /id="cwCombinationQueue"/);
  assert.match(index, /id="cwReviewGrid"/);
  assert.match(index, /实拍产品图 \+ 成品参考图 → 平铺母版图/);
  assert.match(index, /平铺图 A \+ B \+ C… \+ 组合参考图 → 多 SKU 组合图/);
  assert.doesNotMatch(index, /childrenwearMasterNote|childrenwearModelNote|补充要求/);
  assert.match(index, /id="childrenwearAssetPickerModal"/);
  assert.doesNotMatch(index, /class="sidebar-preview-control"/);
  assert.ok((index.match(/data-image-preview-size/g) || []).length >= 5);
  assert.doesNotMatch(index, /data-open-childrenwear-library=/);
  assert.doesNotMatch(index, /childrenwear-hero/);
  assert.match(renderer, /function setChildrenwearAssetTab/);
  assert.match(renderer, /function setChildrenwearProductionTab/);
  assert.match(renderer, /state\.childrenwearDrafts\[stage\]\.unshift\(draft\)/);
  assert.match(renderer, /function cwOldestDraft/);
  assert.match(renderer, /function cwRemoveLastSelectedSource/);
  assert.match(renderer, /data-cw-remove-last-source/);
  assert.match(renderer, /async function runCwBatch\(stage, mode = 'generate'\)/);
  assert.doesNotMatch(renderer, /function flagCurrentCwCompare/);
  assert.doesNotMatch(renderer, /function markCwReviewItemNeedsRegeneration/);
  assert.match(renderer, /function toggleAllChildrenwearLibraryItems/);
  assert.match(renderer, /function prepareChildrenwearFolderUpload/);
  assert.match(renderer, /function parseChildrenwearStylePackage/);
  assert.match(renderer, /function importChildrenwearStylePackage/);
  assert.equal((index.match(/data-import-childrenwear-style-package/g) || []).length, 4);
  assert.equal((index.match(/>按用途文件夹导入<\/button>/g) || []).length, 5);
  assert.doesNotMatch(index, /data-open-childrenwear-production="master">进入生成平铺图/);
  for (const folderName of ['实拍图', '成品图', '模特图', '场景图', '组合图']) assert.match(renderer, new RegExp(`${folderName}:`));
  assert.match(index, /data-cw-model-background="model_reference"/);
  assert.match(index, /data-cw-model-background="white"/);
  assert.match(index, /data-cw-model-background="scene_reference"/);
  assert.match(renderer, /function renameChildrenwearLibraryFolder/);
  assert.match(renderer, /避免素材被合并/);
  assert.match(renderer, /function renderCwQueue/);
  assert.match(renderer, /childrenwearQueueVisibleLimits: \{ master: 36, model: 36, combination: 36 \}/);
  assert.match(renderer, /const renderedDrafts = visibleDrafts\.slice\(0, visibleLimit\)/);
  assert.match(renderer, /data-cw-queue-more/);
  assert.match(renderer, /function syncCwDraftsFromTasks/);
  assert.match(renderer, /const taskByMasterPath = new Map/);
  assert.match(renderer, /task\.modelOutputs/);
  assert.match(renderer, /task\.combinationOutputs/);
  assert.match(renderer, /saved-\$\{stage\}:\$\{task\.folder\}:\$\{output\.id\}/);
  assert.match(renderer, /output\.masterPaths\?\.length/);
  assert.match(renderer, /function cwFilteredDrafts/);
  assert.doesNotMatch(renderer, /function markCwReviewItemNeedsRegeneration/);
  assert.match(renderer, /function cwCompareQueue/);
  assert.match(renderer, /task\.masterThumbnailUrl/);
  assert.match(renderer, /item\.thumbnailUrl \|\| item\.url/);
  assert.match(renderer, /function runCwBatch/);
  assert.match(renderer, /generateChildrenwearBatch/);
  assert.match(renderer, /正在提交整批任务/);
  assert.doesNotMatch(renderer, /runClientConcurrency\(cwTaskGroups, cwConcurrency/);
  assert.match(bridge, /generateChildrenwearBatch/);
  assert.match(bridge, /getChildrenwearTask/);
  assert.match(server, /'generateChildrenwearBatch'/);
  assert.match(server, /getChildrenwearTask/);
  assert.match(renderer, /function scheduleChildrenwearTaskRefresh/);
  assert.match(renderer, /function cwReviewItemForDraft/);
  assert.match(renderer, /reviewIndex\.byId\.get/);
  assert.match(renderer, /void scheduleChildrenwearTaskRefresh\(\)/);
  assert.match(renderer, /applyCwBatchTaskResult\(stage, completedDraft, progress\.itemResult\)/);
  assert.match(renderer, /function mergeCwGeneratedTaskSnapshot/);
  assert.match(renderer, /window\.caishen\.getChildrenwearTask\(value\)/);
  assert.match(renderer, /function applyChildrenwearTaskSnapshots/);
  assert.match(renderer, /function patchCwQueueTaskResults/);
  assert.match(renderer, /current\.replaceWith\(replacement\)/);
  assert.match(renderer, /renderChildrenwearTaskResults\(changedFolderKeys\)/);
  assert.match(renderer, /function flushChildrenwearTaskRefresh/);
  const batchStart = renderer.indexOf('async function runCwBatch');
  const batchEnd = renderer.indexOf('\nasync function ', batchStart + 1);
  const batchSource = renderer.slice(batchStart, batchEnd > batchStart ? batchEnd : undefined);
  assert.doesNotMatch(batchSource, /await flushChildrenwearTaskRefresh\(\)/);
  assert.match(renderer, /updateCwQueueProgress\(stage, draft\)/);
  assert.match(renderer, /items: drafts\.map\(draft => cwDraftGenerationPayload\(stage, draft\)\)/);
  assert.match(renderer, /options\.resultsOnly/);
  assert.doesNotMatch(renderer, /for \(const draft of drafts\) await runCwDraft\(stage, draft\)/);
  assert.match(renderer, /function regenerateCwReviewItem/);
  assert.match(renderer, /childrenwearReviewVisibleGroupLimit: 12/);
  assert.match(renderer, /data-cw-review-more-groups/);
  assert.match(renderer, /if \(currentPage === 'childrenwear'\) \{/);
  assert.doesNotMatch(renderer, /for \(const stage of Object\.keys\(CW_STAGE_META\)\) \{\s*renderCwSource\(stage\);\s*renderCwQueue\(stage\);/);
  assert.match(renderer, /function cwCompareSources/);
  assert.match(renderer, /add\('result', '生成平铺母版图', item\.url, 'result', true, item\.previewUrl\)/);
  assert.match(renderer, /const primaryKey = sources\.find\(source => source\.primary\)/);
  assert.match(renderer, /function toggleCwCompareSource/);
  assert.match(renderer, /function reorderCwCompareSource/);
  assert.match(renderer, /data-cw-compare-toggle/);
  assert.match(renderer, /ondragstart/);
  assert.match(renderer, /function openCwCompare/);
  assert.match(renderer, /function setCwCompareActual/);
  assert.match(renderer, /async function loadCwCompareOriginal/);
  assert.match(renderer, /data-original-src/);
  assert.match(renderer, /source\.previewUrl \|\| source\.url/);
  assert.match(renderer, /高清审核/);
  assert.doesNotMatch(renderer, /data-cw-review-open=/);
  assert.doesNotMatch(renderer, /data-cw-review-flag=/);
  assert.doesNotMatch(renderer, /class="cw-review-card-actions"/);
  assert.match(renderer, /renameChildrenwearTask/);
  assert.match(renderer, /function deleteCwDraftCards/);
  assert.match(renderer, /deleteChildrenwearTasks\(persistentFolders\)/);
  assert.match(renderer, /永久删除任务/);
  assert.match(renderer, /平铺图、模特图、组合图、任务素材、生成证据和人工审核记录/);
  assert.match(renderer, /taskFolders\.has/);
  assert.match(bridge, /deleteChildrenwearTasks/);
  assert.match(server, /deleteChildrenwearTasks/);
  assert.match(bridge, /analyzeChildrenwearAssets/);
  assert.match(server, /'analyzeChildrenwearAssets'/);
  assert.match(index, /id="childrenwearAutoAnalysisEnabled"/);
  assert.match(index, /id="childrenwearAutoAnalysisInterval"/);
  assert.match(index, /id="runChildrenwearAnalysisScanButton"/);
  assert.match(renderer, /scanPendingChildrenwearAnalysis/);
  assert.match(renderer, /intervalInput\.disabled = false/);
  assert.doesNotMatch(renderer, /intervalInput\.disabled = !enabled/);
  assert.match(bridge, /scanPendingChildrenwearAnalysis/);
  assert.match(server, /'scanPendingChildrenwearAnalysis'/);
  assert.match(renderer, /llmPriceMinMinor/);
  assert.match(renderer, /upstreamAnalysisCostCnyMicro/);
  assert.match(renderer, /下载整个款式文件夹/);
  assert.match(renderer, /function cwNextTaskCode/);
  assert.match(index, /批量下载选中款式/);
  assert.match(renderer, /downloadFolders/);
  assert.match(bridge, /downloadChildrenwearFolders/);
  assert.match(renderer, /chooseAssetFolder/);
  assert.match(renderer, /listImageLibrary/);
  assert.match(renderer, /function refreshChildrenwearLibraryAfterImport/);
  assert.match(renderer, /refresh: true, throwOnError: true/);
  assert.match(renderer, /await refreshChildrenwearLibraryAfterImport\(key\)/);
  assert.match(renderer, /function setImagePreviewSize/);
  assert.match(renderer, /function normalizeWorkspaceBackgroundColor/);
  assert.match(renderer, /function applyWorkspaceBackgroundColor/);
  assert.match(renderer, /function workspaceSurfaceColor/);
  assert.match(renderer, /--workspace-surface/);
  assert.match(renderer, /new window\.EyeDropper\(\)\.open\(\)/);
  assert.match(renderer, /scopedStorageKey\(WORKSPACE_BACKGROUND_STORAGE_KEY\)/);
  assert.match(renderer, /bindWorkspaceBackgroundControls\(\)/);
  assert.equal((index.match(/data-cw-queue-date-filter/g) || []).length, 3);
  assert.match(index, /id="cwReviewDateFilter"/);
  assert.match(renderer, /childrenwearQueueDateFilters:\s*\{ master: 'all', model: 'all', combination: 'all' \}/);
  assert.match(renderer, /childrenwearReviewDateFilter:\s*'all'/);
  assert.match(renderer, /function cwTaskDateKey/);
  assert.match(renderer, /function cwTaskDateOptions/);
  assert.match(renderer, /全部日期（\$\{items\.length\}）/);
  assert.match(renderer, /state\.childrenwearQueueDateFilters\[stage\]/);
  assert.match(renderer, /state\.childrenwearReviewDateFilter/);
  assert.match(index, /id="imageHoverPreviewViewport"/);
  assert.match(index, /id="imageHoverLens"/);
  assert.match(index, /id="brandDialogModal"/);
  assert.match(index, /<b>多嘻噜卡科技<\/b>/);
  assert.match(renderer, /const updateMagnifiedPreview/);
  assert.match(renderer, /const zoomFactor = 1\.7/);
  assert.match(renderer, /const sizeMagnifierPane/);
  assert.match(renderer, /--image-preview-width/);
  assert.match(renderer, /--image-preview-height/);
  assert.match(renderer, /data-preview-src=/);
  assert.match(renderer, /function brandConfirm/);
  assert.match(renderer, /function brandPrompt/);
  assert.doesNotMatch(renderer, /window\.(?:alert|confirm|prompt)\s*\(/);
  assert.match(bridge, /async function chooseAssetFolder/);
  assert.match(bridge, /window\.showDirectoryPicker/);
  assert.match(bridge, /async function readDirectoryHandle/);
  assert.match(bridge, /listImageLibrary:/);
  assert.match(bridge, /renameAssetFolder/);
  assert.match(styles, /\.cw-production-panel/);
  assert.match(styles, /\.cw-task-card/);
  assert.match(styles, /\.cw-review-card/);
  assert.match(styles, /\.cw-review-group/);
  assert.doesNotMatch(styles, /\.cw-task-card \{[^}]*content-visibility:\s*auto/);
  assert.match(styles, /\.cw-task-card \{[^}]*contain:\s*layout paint/);
  assert.match(styles, /\.cw-task-card > header label \{[^}]*flex:\s*1 1 auto/);
  assert.match(styles, /\.cw-task-title-line \{[^}]*grid-template-columns:\s*minmax\(0, 1fr\) auto/);
  assert.match(styles, /\.cw-task-title-line > b \{[^}]*text-overflow:\s*ellipsis[^}]*white-space:\s*nowrap[^}]*word-break:\s*keep-all/);
  assert.match(styles, /\.cw-review-group \{[^}]*content-visibility:\s*auto/);
  assert.match(styles, /\.cw-review-card \{[^}]*content-visibility:\s*auto/);
  assert.match(styles, /grid-template-columns: repeat\(auto-fill, minmax\(168px, 1fr\)\)/);
  assert.match(renderer, /function cwReviewTaskMetricsHtml/);
  assert.match(renderer, /合并并发重叠时间后的实际生成处理时长/);
  assert.match(renderer, /childrenwearReviewGroupLimits/);
  assert.match(renderer, /data-cw-review-more/);
  assert.match(server, /runtime\.isWorkspacePath\(source\) \|\| runtime\.isOutputPath\(source\)/);
  assert.match(server, /realPhotoPath:\s*managedPath/);
  assert.match(server, /referencePath:\s*managedPath/);
  assert.match(server, /modelReferencePath:\s*managedPath/);
  assert.match(renderer, /task\.realPhotoPath/);
  assert.match(styles, /\.childrenwear-review-page\.active\s*\{\s*display:\s*grid/);
  assert.match(styles, /\.childrenwear-review-page\s*\{[^}]*grid-template-rows:\s*auto auto minmax\(0, 1fr\)[^}]*overflow:\s*hidden/);
  assert.match(styles, /\.cw-review-grid\s*\{[^}]*min-height:\s*0[^}]*overflow:\s*auto/);
  assert.match(styles, /\.cw-review-toolbar h2 \{\s*font-size:\s*18px/);
  assert.match(styles, /\.cw-review-filters button \{[^}]*font-size:\s*13px/);
  assert.match(styles, /\.cw-review-group-head h3 \{[^}]*font-size:\s*15px/);
  assert.match(styles, /\.cw-review-task-summary b \{[^}]*font-size:\s*13px/);
  assert.match(styles, /\.cw-review-card > label b \{[^}]*font-size:\s*13px/);
  assert.match(styles, /\.cw-date-filter select \{[^}]*min-width:\s*150px/);
  assert.match(styles, /\.sidebar-theme-controls/);
  assert.match(styles, /\.cw-compare-dialog/);
  assert.match(styles, /\.cw-compare-panes/);
  assert.match(styles, /\.cw-compare-source-picker/);
  assert.match(styles, /\.cw-compare-pane\.drop-target/);
  assert.match(styles, /\.childrenwear-picker-modal/);
  assert.match(styles, /\.childrenwear-folder-rename/);
  assert.match(styles, /grid-template-columns: 220px minmax\(0, 1fr\)/);
  assert.match(styles, /\.childrenwear-library-items \{ grid-template-columns: repeat\(auto-fill, 146px\)/);
  assert.match(styles, /\.topbar \{[\s\S]*?background: var\(--navy\)/);
  assert.match(styles, /width: min\(var\(--image-preview-width, 38vw\), 50vw\)/);
  assert.match(styles, /max-height: 76vh/);
  assert.match(styles, /\.image-hover-lens/);
  assert.match(styles, /\.brand-dialog-modal/);
  assert.ok(logo.size > 1000);
});
