const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const path = require('node:path');

test('web app exposes Taobao publish assistant page and bridge methods', async () => {
  const index = await fs.readFile(path.join(__dirname, '../../web/index.html'), 'utf8');
  const bridge = await fs.readFile(path.join(__dirname, '../../web/src/api-bridge.js'), 'utf8');
  const renderer = await fs.readFile(path.join(__dirname, '../../web/src/renderer.js'), 'utf8');
  const styles = await fs.readFile(path.join(__dirname, '../../web/src/styles.css'), 'utf8');
  const server = await fs.readFile(path.join(__dirname, '../src/server.js'), 'utf8');

  assert.match(index, /page-taobao-publish/);
  assert.match(index, /taobaoPublishTaskList/);
  assert.match(index, /taobaoCategoryEditor/);
  assert.match(bridge, /getTaobaoPublishSettings/);
  assert.match(bridge, /saveTaobaoPublishSettings/);
  assert.match(bridge, /queueTaobaoPublishTask/);
  assert.match(bridge, /saveTitleForTask/);
  assert.match(bridge, /execCommand\('copy'\)/);
  assert.match(renderer, /generateTitleForTask\(\{ folder: task\.folder, category \}\)/);
  assert.match(renderer, /taobaoCategoryQuickSelect/);
  assert.match(renderer, /taobaoTaskStoreSelect/);
  assert.match(renderer, /目标淘宝店铺/);
  assert.match(renderer, /taobaoTaskMetaLine/);
  assert.match(renderer, /目标店铺/);
  assert.match(renderer, /执行设备/);
  assert.match(renderer, /failureReason/);
  assert.match(renderer, /storeId/);
  assert.match(renderer, /function taobaoStoresForCurrentUser/);
  assert.match(renderer, /store\.ownerUserId === state\.currentUser\?\.id/);
  assert.match(renderer, /const stores = taobaoStoresForCurrentUser\(\)/);
  assert.match(renderer, /localPublisher/);
  assert.doesNotMatch(renderer, /id="taobaoTaskCategorySelect"/);
  assert.match(renderer, /renderTaobaoPublishPage/);
  assert.match(renderer, /正在打开淘宝/);
  assert.match(renderer, /正在填写模板/);
  assert.match(renderer, /发布失败/);
  assert.match(renderer, /需要人工处理/);
  assert.match(renderer, /模板未配置/);
  assert.match(renderer, /taobaoPublishBlockedTasks/);
  assert.match(renderer, /blockedTasks/);
  assert.match(renderer, /saveActiveTaobaoCategoryTemplate/);
  assert.match(renderer, /queueActiveTaobaoPublishTask/);
  assert.match(renderer, /renderTaobaoPublishDiagnostics/);
  assert.match(renderer, /renderTaobaoExecutionSummary/);
  assert.match(renderer, /renderTaobaoExecutionTimeline/);
  assert.match(renderer, /task\.timeline/);
  assert.match(renderer, /diagnosticScreenshotUrl/);
  assert.match(renderer, /查看发布器截图/);
  assert.match(renderer, /renderTaobaoPublisherDevices/);
  assert.match(renderer, /taobaoPublisherDeviceList/);
  assert.match(renderer, /appVersion/);
  assert.match(renderer, /发布器版本/);
  assert.match(renderer, /最后在线/);
  assert.match(renderer, /本地发布器执行信息/);
  assert.match(renderer, /尝试次数/);
  assert.match(renderer, /更新时间/);
  assert.match(renderer, /截图路径/);
  assert.match(renderer, /extensionId/);
  assert.match(renderer, /copyTaobaoPublishDiagnostics/);
  assert.match(renderer, /data-copy-title/);
  assert.match(renderer, /title-task-manual-title/);
  assert.match(renderer, /data-title-task-action="save-title"/);
  assert.match(renderer, /saveTitleForTask/);
  assert.match(renderer, /applyTaobaoDiagnosticsSelectors/);
  assert.match(renderer, /taobaoDiagnosticsImport/);
  assert.match(renderer, /name="categoryKeyword"/);
  assert.match(renderer, /name="categoryPath"/);
  assert.match(renderer, /name="brandName"/);
  assert.match(renderer, /name="modelName"/);
  assert.match(renderer, /categoryPath.*split\('\\n'\)/);
  assert.match(renderer, /importTaobaoDiagnosticsButton/);
  assert.match(renderer, /notifyTaobaoExtensionPoll/);
  assert.match(renderer, /syncTaobaoExtensionOptions/);
  assert.match(renderer, /CAISHEN_TAOBAO_WEB_SYNC/);
  assert.match(renderer, /CAISHEN_TAOBAO_WEB_TRIGGER/);
  assert.match(renderer, /TAOBAO_SELECTOR_FIELDS/);
  assert.match(renderer, /collectTaobaoSelectors/);
  assert.match(renderer, /categorySearch/);
  assert.match(renderer, /categorySearchButton/);
  assert.match(renderer, /categoryResult/);
  assert.match(renderer, /storeName/);
  assert.match(renderer, /当前店铺名文本/);
  assert.match(renderer, /customFields/);
  assert.match(renderer, /parseJsonArrayField/);
  assert.match(renderer, /mainImages/);
  assert.match(renderer, /saveDraft/);
  assert.match(renderer, /visibleFields/);
  assert.match(renderer, /visibleSelects/);
  assert.match(renderer, /JSON\.stringify\(buttons/);
  assert.match(renderer, /validationError/);
  assert.match(renderer, /frameCandidates/);
  assert.match(renderer, /taskDetail\.frame/);
  assert.match(renderer, /JSON\.stringify\(frames/);
  assert.match(styles, /grid-template-areas:\s*"tasks config detail"/);
  assert.match(styles, /\.taobao-category-select/);
  assert.match(styles, /\.taobao-category-panel\s*\{[\s\S]*overflow: auto/);
  assert.match(styles, /\.taobao-category-editor\s*\{[\s\S]*flex: 0 0 auto/);
  assert.match(styles, /\.taobao-publisher-devices/);
  assert.match(styles, /\.taobao-publisher-device-card/);
  assert.match(styles, /\.taobao-execution-timeline/);
  assert.match(styles, /\.taobao-template-form\s*\{[\s\S]*grid-template-columns: repeat\(2, minmax\(0, 1fr\)\)/);
  assert.match(styles, /\.taobao-template-form\s*\{[\s\S]*max-height: min\(58vh, 620px\)/);
  assert.match(server, /runTaobaoPublishWithToken/);
  assert.match(server, /\/api\/taobao\/publish\/extension-options/);
  assert.match(server, /userId:\s*user\.id/);
  assert.match(server, /ownerUserId:\s*context\?\.user\?\.id/);
  assert.match(server, /storeId:\s*String\(payload\?\.storeId/);
  assert.match(server, /requireStore:\s*true/);
  assert.match(server, /requireStoreOwner:\s*true/);
  assert.match(server, /claimedUser = await auth\.userFromRequest\(req\)/);
  assert.match(server, /claimedUser\.id !== req\.body\?\.userId/);
  assert.match(server, /app\.get\('\/api\/taobao\/publish\/tasks',/);
  assert.match(server, /requestedUser = await auth\.userFromRequest\(req\)/);
  assert.match(server, /requestedUser\.id !== userId/);
  assert.match(server, /runTaobaoPublishWithToken\(token, async \(\) => \{[\s\S]*?runtime\.listTaobaoPublishTasks\(\{[\s\S]*?userId/);
  assert.match(server, /\/images\/:group\/:index/);
  assert.match(await fs.readFile(path.join(__dirname, '../src/runtime.js'), 'utf8'), /detail: saved\.detail \|\| \{\}/);
  assert.ok(server.indexOf("app.post('/api/taobao/publish/claim'") < server.indexOf("app.use('/api'"));
  assert.ok(server.indexOf("app.get('/api/taobao/publish/tasks'") < server.indexOf("app.use('/api'"));
});
