const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const root = path.resolve(__dirname, '..');
const manifest = JSON.parse(fs.readFileSync(path.join(root, 'manifest.json'), 'utf8'));
const background = fs.readFileSync(path.join(root, 'src/background.js'), 'utf8');
const content = fs.readFileSync(path.join(root, 'src/content.js'), 'utf8');
const shared = fs.readFileSync(path.join(root, 'src/shared.js'), 'utf8');
const webBridge = fs.readFileSync(path.join(root, 'src/web-bridge.js'), 'utf8');
const popup = fs.readFileSync(path.join(root, 'src/popup.html'), 'utf8');
const popupJs = fs.readFileSync(path.join(root, 'src/popup.js'), 'utf8');
const packageJson = JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf8'));

assert.equal(manifest.manifest_version, 3);
assert.equal(manifest.background.service_worker, 'src/background.js');
assert.ok(manifest.host_permissions.includes('https://item.upload.taobao.com/*'));
assert.ok(manifest.host_permissions.includes('http://66.42.101.154/*'));
assert.ok(manifest.permissions.includes('debugger'));
assert.ok(manifest.permissions.includes('downloads'));
assert.ok(!manifest.host_permissions.includes('http://127.0.0.1/*'));
assert.ok(!manifest.host_permissions.includes('http://localhost/*'));
assert.ok(manifest.content_scripts.some(item => item.js.includes('src/web-bridge.js') && item.matches.includes('http://66.42.101.154/*')));
assert.ok(manifest.content_scripts.some(item => item.js.includes('src/content.js') && item.all_frames === true));
assert.ok(manifest.content_scripts.some(item => item.js.includes('src/content.js') && item.matches.includes('https://*.taobao.com/*')));
assert.match(shared, /http:\/\/66\.42\.101\.154:8788/);
assert.match(shared, /refreshToken/);
assert.match(shared, /ensureToken/);
assert.doesNotMatch(shared, /127\.0\.0\.1:8790/);
assert.doesNotMatch(popup, /baseUrl/);
assert.match(popup, /id="token"/);
assert.match(popup, /refreshTokenButton/);
assert.match(background, /\/api\/taobao\/publish\/claim/);
assert.match(background, /CAISHEN_TAOBAO_TRIGGER_POLL/);
assert.match(background, /CAISHEN_TAOBAO_FETCH_IMAGE/);
assert.match(background, /CAISHEN_TAOBAO_TRUSTED_CLICK/);
assert.match(background, /CAISHEN_TAOBAO_UPLOAD_FILES/);
assert.match(background, /Page\.setInterceptFileChooserDialog/);
assert.match(background, /Page\.fileChooserOpened/);
assert.match(background, /DOM\.setFileInputFiles/);
assert.match(background, /uploadStage/);
assert.match(background, /throw new Error\(`\$\{stage\}: \$\{message\}`\)/);
assert.match(background, /async function clickPickerUploadEntryInFrames/);
assert.match(background, /target: \{ tabId, allFrames: true \}/);
assert.match(background, /const wanted = \['本地上传', '上传本地图片', '点击上传'\]/);
assert.match(background, /const pickerClick = await clickPickerUploadEntryInFrames\(tabId\)/);
assert.match(background, /if \(!pickerClick\.clicked\) throw firstError/);
assert.match(background, /Browser\.setDownloadBehavior/);
assert.match(background, /Runtime\.evaluate/);
assert.match(background, /Browser\.downloadWillBegin/);
assert.match(background, /Browser\.downloadProgress/);
assert.match(background, /uploadDownloadPath/);
assert.match(background, /message\.useCachedUploadFiles/);
assert.match(background, /chrome\.debugger\.attach/);
assert.match(background, /Input\.dispatchMouseEvent/);
assert.match(background, /chrome\.debugger\.detach/);
assert.match(background, /let debuggerTabId/);
assert.match(background, /function ensureDebuggerAttached/);
assert.match(background, /await ensureDebuggerAttached\(tabId\)/);
assert.match(background, /await detachDebugger\(\)/);
assert.match(background, /\/images\/\$\{group\}\/\$\{index\}/);
assert.match(background, /CAISHEN_TAOBAO_STATUS/);
assert.match(background, /schedulePoll/);
assert.match(background, /clearLastError/);
assert.match(background, /chrome\.storage\.local\.remove\(\['lastError', 'lastErrorAt'\]\)/);
assert.match(background, /setTimeout/);
assert.match(background, /Math\.max\(30000, options\.pollSeconds \* 1000\)/);
assert.match(background, /chrome\.tabs\.onRemoved\.addListener/);
assert.match(background, /chrome\.tabs\.onUpdated\.addListener/);
assert.match(background, /clearActiveTask/);
assert.match(background, /trySendTaskToActiveTab/);
assert.match(background, /activeFrameId/);
assert.match(background, /let activeTaskDispatched = false/);
assert.match(background, /if \(!activeTask \|\| !activeTabId \|\| activeTaskDispatched\) return false/);
assert.match(background, /activeTaskDispatched = true/);
assert.match(background, /activeTaskDispatched = false/);
assert.match(background, /sender\.tab\?\.id === activeTabId && !activeTaskDispatched/);
assert.match(background, /lastFrameCandidates/);
assert.match(background, /findPublishFrame/);
assert.match(background, /frameCandidates/);
assert.match(background, /frame-selected/);
assert.match(background, /allFrames: true/);
assert.match(background, /frameId: activeFrameId/);
assert.match(background, /findExistingPublishTab/);
assert.match(background, /chrome\.tabs\.query\(\{ url: 'https:\/\/item\.upload\.taobao\.com\/\*' \}\)/);
assert.match(background, /\\\/sell\\\/ai\\\/category\\\.htm/);
assert.doesNotMatch(background, /\/sell\/\(ai\\\/category\|v2\\\/publish\)\\\.htm/);
assert.match(background, /chrome\.tabs\.update\(existingTab\.id, \{ url: publishUrl, active: true \}\)/);
assert.match(background, /chrome\.tabs\.create\(\{ url: publishUrl, active: true \}\)/);
assert.match(background, /chrome\.windows\.update\(tab\.windowId, \{ focused: true \}\)/);
assert.match(background, /injectContentScript/);
assert.match(background, /chrome\.scripting\.executeScript/);
assert.match(background, /CAISHEN_TAOBAO_POPUP_DIAGNOSTICS/);
assert.match(background, /CAISHEN_TAOBAO_COLLECT_DIAGNOSTICS/);
assert.match(content, /input\[type="file"\]/);
assert.match(content, /标题/);
assert.match(content, /价格/);
assert.match(content, /上传图片/);
assert.match(content, /保存草稿/);
assert.match(content, /dataUrlToFile/);
assert.match(content, /selectors\(task\)/);
assert.match(content, /selectOptionByText/);
assert.match(content, /isSelectLike/);
assert.match(content, /setSelectValue/);
assert.match(content, /if \(isSelectLike\(selected\)\) return setSelectValue\(selected, value\)/);
assert.match(content, /clickElement/);
assert.match(content, /trustedClickElement/);
assert.match(content, /function findUploadTrigger/);
assert.match(content, /async function uploadWithFileChooser/);
assert.match(content, /async function uploadWithDynamicInput/);
assert.match(content, /async function uploadWithTaobaoPicker/);
assert.match(content, /function findTaobaoPickerUploadTrigger/);
assert.match(content, /function collectTaobaoPickerUploadCandidates/);
assert.match(content, /async function uploadWithChooserTarget/);
assert.match(content, /let uploadAttempt = \{\}/);
assert.match(content, /uploadAttempt\.lastChooserTarget/);
assert.match(content, /uploadAttempt\.taobaoPicker/);
assert.match(content, /async function waitForTaobaoPickerUploadTrigger/);
assert.match(content, /async function waitForTaobaoPickerUploadTrigger\(originalTrigger, timeoutMs = 12000\)/);
assert.match(content, /await waitForTaobaoPickerUploadTrigger\(trigger\)/);
assert.match(content, /candidates: collectTaobaoPickerUploadCandidates\(trigger\)/);
assert.match(content, /label === '本地上传'/);
assert.doesNotMatch(content, /const wanted = \['本地上传', '上传本地图片', '点击上传', '上传'\]/);
assert.match(content, /await trustedClickElement\(trigger, '上传图片'\)/);
assert.match(content, /#struct-threeToFourImages/);
assert.match(content, /pageUploadSections/);
assert.match(content, /!pageUploadSections\.some/);
assert.match(content, /uploadMode: 'taobao-picker'/);
assert.match(content, /chooserMode: response\.mode \|\| mode/);
assert.match(content, /uploadWithChooserTarget\(task, uploadEntry, images, group, step, 'taobao-picker'\)/);
assert.match(content, /return uploadWithChooserTarget\(task, trigger, images, group, step, 'direct'\)/);
assert.match(content, /await uploadWithTaobaoPicker\(task, mainTrigger/);
assert.match(content, /await uploadWithTaobaoPicker\(task, ratioTrigger/);
assert.match(content, /async function uploadWithDrop/);
assert.match(content, /\['dragenter', 'dragover', 'drop'\]/);
assert.match(content, /new DragEvent\(type/);
assert.match(content, /uploadMode: 'drop'/);
assert.match(content, /await uploadWithDrop\(task, mainTrigger/);
assert.match(content, /await uploadWithDrop\(task, ratioTrigger/);
assert.match(content, /waitForNewFileInput/);
assert.match(content, /uploadWithDynamicInput\(task, mainTrigger/);
assert.match(content, /uploadWithDynamicInput\(task, ratioTrigger/);
assert.match(content, /CAISHEN_TAOBAO_UPLOAD_FILES/);
assert.match(content, /useCachedUploadFiles: true/);
assert.match(content, /#struct-mainImagesGroup/);
assert.match(content, /#sell-field-threeToFourImages/);
assert.match(content, /function trustedClickPoint/);
assert.match(content, /preferredText/);
assert.match(content, /target\.querySelectorAll\('\*'\)/);
assert.match(content, /currentWindow\.frameElement/);
assert.match(content, /frameRect\.left/);
assert.match(content, /categoryAttempt\.trustedClicks/);
assert.match(content, /uploadAttempt/);
assert.match(content, /CAISHEN_TAOBAO_TRUSTED_CLICK/);
assert.match(content, /await trustedClickElement\(manualSelected, keyword\)/);
assert.match(content, /scrollIntoView/);
assert.match(content, /aria-disabled/);
assert.match(content, /element\.click\?\.\(\)/);
assert.doesNotMatch(content, /for \(const type of \['pointerdown', 'mousedown', 'mouseup', 'click'\]\)/);
assert.match(content, /waitForButton/);
assert.match(content, /fallbackAllImages/);
assert.match(content, /fileInputFromSelector/);
assert.match(content, /queryFileInput/);
assert.match(content, /uploadBusyElements/);
assert.match(content, /waitForUploadSettled/);
assert.match(content, /upload-settled/);
assert.match(content, /collectDiagnostics/);
assert.match(content, /collectVisibleFields/);
assert.match(content, /collectVisibleSelects/);
assert.match(content, /fillCustomFields/);
assert.match(content, /customFields/);
assert.match(content, /saveDraft/);
assert.match(content, /waitForDraftSaved/);
assert.match(content, /confirmSaveDraftIfPrompted/);
assert.match(content, /confirmSaveDraftIfPrompted\(button\)/);
assert.match(content, /element !== excludedButton/);
assert.doesNotMatch(content, /confirmSaveDraftIfPrompted\(\)[\s\S]*?findButton\(\[[\s\S]*?'保存'[\s\S]*?\]\)/);
assert.match(content, /STATUS\.saved/);
assert.match(content, /savedAt/);
assert.match(content, /findValidationError/);
assert.match(content, /isCategoryEntryPage/);
assert.match(content, /function isTaobaoLoginPage/);
assert.ok(content.includes("return /login\\.taobao\\.com/i.test(location.hostname)"));
assert.match(content, /if \(isTaobaoLoginPage\(\)\) throw fail\([^\n]+, 'login'\)/);
assert.doesNotMatch(content, /\/category\\\.htm\/i\.test\(location\.href\)/);
assert.match(content, /selectTaobaoCategory/);
assert.match(content, /preparePublishForm/);
assert.match(content, /scoreCategoryCandidate/);
assert.match(content, /ownKeywordHit/);
assert.match(content, /score \+= 60/);
assert.match(content, /categoryOwnLabelIncludesKeyword/);
assert.match(content, /function findConfiguredCategoryCandidate/);
assert.match(content, /findConfiguredCategoryCandidate\(task, keyword\) \|\| findCategoryCandidate\(keyword\)/);
assert.doesNotMatch(content, /query\(selectors\(task\)\.categoryResult\) \|\| findCategoryCandidate\(keyword\)/);
assert.match(content, /function categoryClickTarget/);
assert.match(content, /categoryClickTarget\(item\.element, keyword\)/);
assert.match(content, /function findManualCategoryCandidate/);
assert.match(content, /function findCategoryResultRadio/);
assert.match(content, /async function selectCategoryBrand/);
assert.match(content, /function findCategoryBrandField/);
assert.match(content, /function findCategoryBrandSearchInput/);
assert.match(content, /function findFirstVisibleBrandOption/);
assert.match(content, /async function trustedClickElementRightEdge/);
assert.match(content, /clickElement\(field\)/);
assert.match(content, /async function waitForCategoryBrandSearchInput/);
assert.match(content, /await waitForCategoryBrandSearchInput\(field\)/);
assert.match(content, /await trustedClickElementRightEdge\(field\)/);
assert.match(content, /let searchInput = await waitForCategoryBrandSearchInput\(field\)/);
assert.doesNotMatch(content, /waitForCategoryBrandSearchInput\(field\) \|\| field/);
assert.match(content, /popupSearchShape/);
assert.match(content, /async function waitForExactVisibleOption/);
assert.match(content, /async function ensureCategorySearchMode/);
assert.match(content, /await trustedClickElement\(searchMode, '\\u641c\\u7d22\\u53d1\\u54c1'\)/);
assert.match(content, /await ensureCategorySearchMode\(task\)/);
assert.match(content, /async function openManualCategorySelector/);
assert.match(content, /closest\('button, \[role="button"\], a'\)/);
assert.match(content, /clickElement\(selectorButton\)/);
assert.match(content, /const optionTarget = categoryClickTarget\(option, label\)/);
assert.match(content, /'\\u4f4f\\u5b85\\u5bb6\\u5177', '\\u67dc\\u7c7b', keyword/);
assert.match(content, /await openManualCategorySelector\(task, keyword\)/);
assert.match(content, /clickElement\(manualContinuation\)/);
assert.ok(content.indexOf('findConfiguredCategoryCandidate(task, keyword) || findCategoryCandidate(keyword)') < content.indexOf('await openManualCategorySelector(task, keyword)'));
assert.match(content, /copyItem=true/);
const waitForPublishFormSource = content.match(/async function waitForPublishForm[\s\S]*?\n}/)?.[0] || '';
assert.doesNotMatch(waitForPublishFormSource, /fileInputs\(\)\.length/);
assert.match(content, /placeholder === '\\u8bf7\\u9009\\u62e9'/);
assert.doesNotMatch(content, /findField\(\['\\u54c1\\u724c'\], selectors\(task\)\.categoryBrand\)/);
assert.match(content, /setNativeValue\(searchInput, brand\)/);
assert.match(content, /waitForExactVisibleOption\('\\u5176\\u4ed6\\u5bb6'/);
assert.match(content, /findFirstVisibleBrandOption\(\)/);
assert.match(content, /const optionTarget = option\.closest\('\[role="option"\], \[role="menuitem"\], li'\)/);
assert.match(content, /clickElement\(optionTarget\)/);
assert.match(content, /async function waitForFieldValue/);
assert.match(content, /await waitForFieldValue\(field, brand\)/);
assert.match(content, /brandSelectionError/);
assert.match(content, /input\[name="p-20000~1"\]/);
assert.match(content, /async function waitForBrandModelField/);
assert.match(content, /await waitForBrandModelField\(\)/);
assert.match(content, /defaults\?\.modelName \|\| task\?\.category\?\.defaults\?\.model \|\| '\\u5176\\u4ed6'/);
assert.match(content, /await waitForFieldValue\(modelField, modelValue, 3000\)/);
assert.match(content, /brandModelError/);
assert.match(content, /await selectCategoryBrand\(task\)/);
assert.match(content, /input\[type="radio"\]/);
assert.match(content, /const resultRadio = findCategoryResultRadio\(selected\)/);
assert.match(content, /await trustedClickElement\(resultRadio\)/);
assert.match(content, /await trustedClickElement\(selected, keyword\)/);
assert.match(content, /const manualSelected = findManualCategoryCandidate\(keyword, selected\)/);
assert.match(content, /categoryAttempt\.manualSelected/);
assert.match(content, /element\.getAttribute\('role'\) !== 'tab'/);
assert.match(content, /!element\.closest\('\[role="tablist"\]'\)/);
assert.match(content, /const confirmationOnly = label => label\.includes/);
assert.match(content, /document\.querySelectorAll\('button, \[role="button"\], a, span, div'\)/);
assert.match(content, /element\.closest\('button, \[role="button"\], a'\) \|\| element/);
assert.match(content, /async function waitForCategoryContinuation/);
assert.match(content, /await waitForCategoryContinuation\(selected, selected\)/);
assert.match(content, /await waitForCategoryContinuation\(null, null\)/);
assert.doesNotMatch(content, /if \(label\.includes\('\\u9009\\u62e9'\)\) return 1/);
assert.match(content, /const directCandidates = candidates\.filter/);
assert.match(content, /clickableCandidates\[0\]\?\.element/);
assert.match(content, /categoryCandidateText/);
assert.match(content, /genericCategoryLabels/);
assert.match(content, /findCategoryAction/);
assert.match(content, /findCategoryContinuation/);
assert.match(content, /categoryActionLabel/);
assert.match(content, /categoryAttempt/);
assert.match(content, /visibleButtons: buttons,[\s\S]*categoryAttempt/);
assert.match(content, /const continuation = await waitForCategoryContinuation\(selected, selected\)/);
assert.match(content, /const fallbackAction = findCategoryAction\(selected, keyword\)/);
assert.ok(content.indexOf('await trustedClickElement(selected, keyword)') < content.indexOf('const continuation = await waitForCategoryContinuation(selected, selected)'));
assert.ok(content.indexOf('const manualSelected = findManualCategoryCandidate(keyword, selected)') < content.indexOf('const continuation = await waitForCategoryContinuation(selected, selected)'));
assert.ok(content.indexOf('const continuation = await waitForCategoryContinuation(selected, selected)') < content.indexOf('const fallbackAction = findCategoryAction(selected, keyword)'));
assert.match(content, /if \(await waitForPublishForm\(3500\)\) return/);
assert.match(content, /label\.includes\('\\u4e0b\\u4e00\\u6b65'\)/);
assert.match(content, /cssSelectorForDiagnostics/);
assert.match(content, /selectorForElement/);
assert.match(content, /CAISHEN_TAOBAO_COLLECT_DIAGNOSTICS/);
assert.match(content, /collectDiagnostics\(error\.step \|\| 'unknown'\)/);
assert.match(content, /KeyboardEvent/);
assert.match(content, /runningTaskId/);
assert.match(content, /if \(runningTaskId === message\.task\?\.id\)/);
assert.doesNotMatch(content, /if \(await preparePublishForm\(task\)\) return/);
assert.doesNotMatch(content, /successKeywords[\s\S]*'\\u8349\\u7a3f'/);
assert.match(webBridge, /CAISHEN_TAOBAO_WEB_TRIGGER/);
assert.match(webBridge, /CAISHEN_TAOBAO_WEB_SYNC/);
assert.match(webBridge, /CAISHEN_TAOBAO_TRIGGER_POLL/);
assert.match(webBridge, /CAISHEN_TAOBAO_POPUP_SAVE/);
assert.doesNotMatch(webBridge, /baseUrl/);
assert.match(webBridge, /token/);
assert.match(popup, /diagnosticsButton/);
assert.match(popup, /copyDiagnosticsButton/);
assert.match(popup, /diagnosticsOutput/);
assert.match(popupJs, /CAISHEN_TAOBAO_POPUP_DIAGNOSTICS/);
assert.match(popupJs, /CAISHEN_TAOBAO_POPUP_REFRESH_TOKEN/);
assert.match(popupJs, /if \(options\.token\)/);
assert.match(popupJs, /令牌已由 Web 端自动同步/);
assert.match(popupJs, /navigator\.clipboard\.writeText/);
assert.match(popup, /token/);
assert.match(packageJson.scripts.package, /package-extension\.ps1/);
assert.ok(fs.existsSync(path.join(root, 'scripts/package-extension.ps1')));

console.log('taobao extension smoke test passed');
